//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ZusiTCPDemoApp.Properties
{
	using System;
	
    //This class was auto-generated by the StronglyTypedResourceBuilder
    //class via a tool like ResGen or Visual Studio.
    //To add or remove a member, edit your .ResX file then rerun ResGen
    //with the /str option, or rebuild your VS project.
    ///<summary>
    ///  A strongly-typed resource class, for looking up localized strings, etc.
    ///summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  
     System.Diagnostics.DebuggerNonUserCodeAttribute(),  
     System.Runtime.CompilerServices.CompilerGeneratedAttribute()]  
    internal /*module*/ class Resources
	{
		private static System.Resources.ResourceManager resourceMan; 
        
		private static System.Globalization.CultureInfo resourceCulture;
        
        ///<summary>
        ///  Returns the cached ResourceManager instance used by this class.
        ///</summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static System.Resources.ResourceManager ResourceManager
		{
		get
			{
		        if (Object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ZusiTCPDemoApp.Properties",  typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
        
        ///<summary>
		///  Overrides the current thread's CurrentUICulture property for all
		///  resource lookups using this strongly typed resource class.
		///</summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static System.Globalization.CultureInfo Culture
		{
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}
        
        ///<summary>
        ///  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1031{\fonttbl{\f0\fnil\fcharset0 Arial;}{\f1\fswiss\fcharset0 Courier New;}{\f2\fnil\fprq1\fcharset0 Courier New;}}
        ///{\colortbl ;\red255\green0\blue0;\red0\green176\blue80;\red165\green165\blue165;\red0\green128\blue0;}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\qc\cf1\b\fs52 Hinweis:\par
        ///\pard\cf0\b0\fs24\par
        ///\ul\b Zur Nutzung des  \cf2 LM Block, bis zu dem die Strecke frei ist\cf0  muss die commandset.ini des TCP-Servers \cf1 ge\&apos;e4ndert werden\cf0 !\p [rest of string was truncated]&quot;;.
        ///</summary>
		internal static string BlockFreiWarnung
		{
			get { return ResourceManager.GetString("BlockFreiWarnung", resourceCulture); }
		} 
	}
}
